### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by nco2k** [maxthetomas/skip-backup-screen#2]
pls

**Comment by 5w14** [comment]
Gosh, github didn't send me any notifications on this issue.

I'll check if it works on 1.20.2-1.20.4

**Comment by 5w14** [comment]
**Release for 1.20.2:** 
https://github.com/maxthetomas/skip-backup-screen/releases/tag/1.1

**Release for 1.20.3 and 1.20.4:**
https://github.com/maxthetomas/skip-backup-screen/releases/tag/1.2
